package com.devpulse.configuration;

import com.devpulse.entity.*;
import com.devpulse.repository.*;
import com.devpulse.service.AlertEvaluationService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;

/**
 * Populates a realistic demo project (services, metrics, incidents,
 * deployments, an alert rule + triggered alert) when DEMO_MODE=true, so the
 * product can be demonstrated without connecting real infrastructure.
 *
 * Idempotent: skips seeding entirely if the demo user already exists, so
 * restarting the app in demo mode doesn't create duplicate data.
 *
 * @Order(2): runs after RoleSeeder, which this depends on.
 */
@Component
@Order(2)
public class DemoDataSeeder implements CommandLineRunner {

    private static final String DEMO_EMAIL = "demo@devpulse.local";
    // Demo-only credential, never a real secret - documented in README/docs/architecture.md.
    private static final String DEMO_PASSWORD = "DemoPass123!";

    private final boolean demoEnabled;
    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final PasswordEncoder passwordEncoder;
    private final ProjectRepository projectRepository;
    private final ServiceRepository serviceRepository;
    private final IncidentRepository incidentRepository;
    private final DeploymentRepository deploymentRepository;
    private final AlertRuleRepository alertRuleRepository;
    private final MetricRepository metricRepository;
    private final AlertEvaluationService alertEvaluationService;

    public DemoDataSeeder(@Value("${devpulse.demo.enabled:false}") boolean demoEnabled,
                           UserRepository userRepository,
                           RoleRepository roleRepository,
                           PasswordEncoder passwordEncoder,
                           ProjectRepository projectRepository,
                           ServiceRepository serviceRepository,
                           IncidentRepository incidentRepository,
                           DeploymentRepository deploymentRepository,
                           AlertRuleRepository alertRuleRepository,
                           MetricRepository metricRepository,
                           AlertEvaluationService alertEvaluationService) {
        this.demoEnabled = demoEnabled;
        this.userRepository = userRepository;
        this.roleRepository = roleRepository;
        this.passwordEncoder = passwordEncoder;
        this.projectRepository = projectRepository;
        this.serviceRepository = serviceRepository;
        this.incidentRepository = incidentRepository;
        this.deploymentRepository = deploymentRepository;
        this.alertRuleRepository = alertRuleRepository;
        this.metricRepository = metricRepository;
        this.alertEvaluationService = alertEvaluationService;
    }

    @Override
    public void run(String... args) {
        if (!demoEnabled) {
            return;
        }
        if (userRepository.existsByEmail(DEMO_EMAIL)) {
            return;
        }

        User demoUser = createDemoUser();
        Project project = createDemoProject(demoUser);
        ServiceEntity apiGateway = createService(project, "API Gateway", "http");
        ServiceEntity orderApi = createService(project, "Order API", "http");
        createService(project, "PostgreSQL", "database");

        seedIncidents(project, orderApi);
        seedDeployments(project);
        seedAlertRuleAndTriggeredAlert(project, apiGateway);
    }

    private User createDemoUser() {
        Role developerRole = roleRepository.findByName("DEVELOPER")
                .orElseThrow(() -> new IllegalStateException("DEVELOPER role missing - RoleSeeder should run first"));

        User user = new User();
        user.setEmail(DEMO_EMAIL);
        user.setPassword(passwordEncoder.encode(DEMO_PASSWORD));
        user.setFirstName("Demo");
        user.setLastName("User");
        user.setRole(developerRole);
        return userRepository.save(user);
    }

    private Project createDemoProject(User owner) {
        Project project = new Project();
        project.setName("DevPulse Demo");
        project.setDescription("Sample project auto-generated by DEMO_MODE for portfolio/demo purposes.");
        project.setRepository("https://github.com/example/devpulse-demo");
        project.setEnvironment("production");
        project.setOwner(owner);
        return projectRepository.save(project);
    }

    private ServiceEntity createService(Project project, String name, String type) {
        ServiceEntity service = new ServiceEntity();
        service.setProject(project);
        service.setName(name);
        service.setType(type);
        service.setHealthStatus("HEALTHY");
        return serviceRepository.save(service);
    }

    private void seedIncidents(Project project, ServiceEntity orderApi) {
        Incident resolved = new Incident();
        resolved.setProject(project);
        resolved.setServiceRef(orderApi);
        resolved.setServiceName(orderApi.getName());
        resolved.setTitle("Order API latency spike after deployment");
        resolved.setDescription("P95 latency increased sharply following a routine deployment.");
        resolved.setSeverity("HIGH");
        resolved.setStatus("RESOLVED");
        resolved.setStartedAt(LocalDateTime.now().minusDays(2));
        resolved.setDetectedAt(LocalDateTime.now().minusDays(2).plusMinutes(4));
        resolved.setResolvedAt(LocalDateTime.now().minusDays(2).plusHours(1));
        resolved.setRootCause("Missing index on orders.customer_id after the latest migration.");
        resolved.setRecommendations("1. Add the missing index\n2. Review migration checklist for index coverage");
        resolved.setConfidenceScore(0.87);
        incidentRepository.save(resolved);

        Incident open = new Incident();
        open.setProject(project);
        open.setTitle("Elevated error rate on checkout flow");
        open.setDescription("Error rate above baseline for the last 15 minutes.");
        open.setSeverity("MEDIUM");
        open.setStatus("INVESTIGATING");
        open.setStartedAt(LocalDateTime.now().minusMinutes(20));
        incidentRepository.save(open);
    }

    private void seedDeployments(Project project) {
        record DeploymentSeed(String version, String status, int daysAgo) {}
        for (DeploymentSeed seed : new DeploymentSeed[]{
                new DeploymentSeed("v1.4.0", "FAILED", 5),
                new DeploymentSeed("v1.4.1", "SUCCESS", 3),
                new DeploymentSeed("v1.4.2", "SUCCESS", 1)
        }) {
            Deployment deployment = new Deployment();
            deployment.setProject(project);
            deployment.setVersion(seed.version());
            deployment.setEnvironment("production");
            deployment.setStatus(seed.status());
            deployment.setBranch("main");
            deployment.setAuthor(DEMO_EMAIL);
            deployment.setStartedAt(LocalDateTime.now().minusDays(seed.daysAgo()));
            deployment.setFinishedAt(LocalDateTime.now().minusDays(seed.daysAgo()).plusMinutes(6));
            deploymentRepository.save(deployment);
        }
    }

    private void seedAlertRuleAndTriggeredAlert(Project project, ServiceEntity apiGateway) {
        AlertRule rule = new AlertRule();
        rule.setProject(project);
        rule.setName("High CPU usage");
        rule.setMetric("cpu_usage_percent");
        rule.setOperator(">");
        rule.setThreshold(80.0);
        rule.setDuration("5m");
        rule.setSeverity("HIGH");
        rule.setEnabled(true);
        alertRuleRepository.save(rule);

        // Reuse the real evaluation pipeline (AlertEvaluationService) rather
        // than hand-crafting an Alert row, so the demo data is produced by
        // the exact same code path real traffic would go through.
        Metric breachingMetric = new Metric();
        breachingMetric.setProject(project);
        breachingMetric.setServiceName(apiGateway.getName());
        breachingMetric.setMetricName("cpu_usage_percent");
        breachingMetric.setMetricValue(91.3);
        breachingMetric.setUnit("%");
        Metric saved = metricRepository.save(breachingMetric);
        alertEvaluationService.evaluate(saved);

        // A handful of healthy historical points so dashboard charts aren't empty.
        for (int i = 6; i >= 1; i--) {
            Metric point = new Metric();
            point.setProject(project);
            point.setServiceName(apiGateway.getName());
            point.setMetricName("cpu_usage_percent");
            point.setMetricValue(35.0 + (i % 3) * 5);
            point.setUnit("%");
            point.setCapturedAt(LocalDateTime.now().minusHours(i));
            metricRepository.save(point);
        }
    }
}
